# ./docker-compose.yml

version: '3'

services: 
  db:
    image: mysql
    environment: 
      MYSQL_USER: root
      MYSQL_DATABASE: quizometro
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "9906:3306"
    networks:
      - mysql-compose-network  
      
  server:
    image: php:7.4-cli
    build:
      dockerfile: Dockerfile
      context: server
    container_name: server
    depends_on: 
      - db
    volumes: 
      - ./server/:/var/www/html
    ports:
      - "8000:80"
    stdin_open: true
    tty: true

networks: 
  mysql-compose-network:
    driver: bridge